/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PrayerStatus = IDL.Variant({
  'pending' : IDL.Null,
  'prayed' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const PrayerRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : PrayerStatus,
  'name' : IDL.Opt(IDL.Text),
  'createdAt' : Timestamp,
  'anonymous' : IDL.Bool,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  'createPrayerRequest' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Text, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'deletePrayerRequest' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'getPrayerRequests' : IDL.Func([], [IDL.Vec(PrayerRequest)], ['query']),
  'updatePrayerRequestStatus' : IDL.Func(
      [IDL.Nat, PrayerStatus],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PrayerStatus = IDL.Variant({
    'pending' : IDL.Null,
    'prayed' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const PrayerRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : PrayerStatus,
    'name' : IDL.Opt(IDL.Text),
    'createdAt' : Timestamp,
    'anonymous' : IDL.Bool,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    'createPrayerRequest' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Text, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'deletePrayerRequest' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'getPrayerRequests' : IDL.Func([], [IDL.Vec(PrayerRequest)], ['query']),
    'updatePrayerRequestStatus' : IDL.Func(
        [IDL.Nat, PrayerStatus],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };